export default {
  Success: 1,
  Failure: 0,
  
  WeightSimple: {
    Strawweight: "Strawweight",
    LightFlyweight: "Light Flyweight",
    Flyweight: "Flyweight",
    SuperFlyweight: "Super Flyweight",
    Bantamweight: "Bantamweight",
    SuperBantamweight: "Super Bantamweight",
    Featherweight: "Featherweight",
    SuperFeatherweight: "Super Featherweight",
    Lightweight: "Lightweight",
    SuperLightweight: "Super Lightweight",
    Welterweight: "Welterweight",
    SuperWelterweight: "Super Welterweight",
    Middleweight: "Middleweight",
    SuperMiddleweight: "Super Middleweight",
    LightHeavyweight: "Light Heavyweight",
    Cruiserweight: "Cruiserweight",
    Heavyweight: "Heavyweight",
  },

  WeightLabel: {
    Strawweight: "Strawweight: 105 pounds (48 kg)",
    LightFlyweight: "Light Flyweight: 108 pounds (49 kg)",
    Flyweight: "Flyweight: 112 pounds (51 kg)",
    SuperFlyweight: "Super Flyweight: 115 pounds (52 kg)",
    Bantamweight: "Bantamweight: 118 pounds (53.5 kg)",
    SuperBantamweight: "Super Bantamweight: 122 pounds (55 kg)",
    Featherweight: "Featherweight: 126 pounds (57 kg)",
    SuperFeatherweight: "Super Featherweight: 130 pounds (59 kg)",
    Lightweight: "Lightweight: 135 pounds (61 kg)",
    SuperLightweight: "Super Lightweight: 140 pounds (63.5 kg)",
    Welterweight: "Welterweight: 147 pounds (67 kg)",
    SuperWelterweight: "Super Welterweight: 154 pounds (70 kg)",
    Middleweight: "Middleweight: 160 pounds (72.5 kg)",
    SuperMiddleweight: "Super Middleweight: 168 pounds (76 kg)",
    LightHeavyweight: "Light Heavyweight: 175 pounds (79 kg)",
    Cruiserweight: "Cruiserweight: 200 pounds (90.7 kg)",
    Heavyweight: "Heavyweight: Unlimited",
  }
}